package main

// Сгенерировано: node scripts/gen-helper-paths.mjs — руками не править.
// Источник — helper/testdata/*.json, снятые настоящим buildConfig.

var allowedPaths = map[string]bool{
	"dns.final":                                    true,
	"dns.independent_cache":                        true,
	"dns.reverse_mapping":                          true,
	"dns.rules[].action":                           true,
	"dns.rules[].domain_suffix[]":                  true,
	"dns.rules[].query_type[]":                     true,
	"dns.rules[].rule_set[]":                       true,
	"dns.rules[].server":                           true,
	"dns.servers[].detour":                         true,
	"dns.servers[].inet4_range":                    true,
	"dns.servers[].inet6_range":                    true,
	"dns.servers[].path":                           true,
	"dns.servers[].server":                         true,
	"dns.servers[].tag":                            true,
	"dns.servers[].type":                           true,
	"dns.strategy":                                 true,
	"experimental.cache_file.enabled":              true,
	"experimental.cache_file.path":                 true,
	"experimental.cache_file.store_fakeip":         true,
	"experimental.cache_file.store_rdrc":           true,
	"experimental.clash_api.default_mode":          true,
	"experimental.clash_api.external_controller":   true,
	"experimental.clash_api.secret":                true,
	"inbounds[].address[]":                         true,
	"inbounds[].auto_route":                        true,
	"inbounds[].listen":                            true,
	"inbounds[].listen_port":                       true,
	"inbounds[].mtu":                               true,
	"inbounds[].stack":                             true,
	"inbounds[].strict_route":                      true,
	"inbounds[].tag":                               true,
	"inbounds[].type":                              true,
	"log.level":                                    true,
	"log.timestamp":                                true,
	"outbounds[].alter_id":                         true,
	"outbounds[].congestion_control":               true,
	"outbounds[].default":                          true,
	"outbounds[].flow":                             true,
	"outbounds[].heartbeat":                        true,
	"outbounds[].idle_session_check_interval":      true,
	"outbounds[].idle_session_timeout":             true,
	"outbounds[].idle_timeout":                     true,
	"outbounds[].interrupt_exist_connections":      true,
	"outbounds[].interval":                         true,
	"outbounds[].method":                           true,
	"outbounds[].obfs.password":                    true,
	"outbounds[].obfs.type":                        true,
	"outbounds[].outbounds[]":                      true,
	"outbounds[].packet_encoding":                  true,
	"outbounds[].password":                         true,
	"outbounds[].security":                         true,
	"outbounds[].server":                           true,
	"outbounds[].server_port":                      true,
	"outbounds[].tag":                              true,
	"outbounds[].tls.alpn[]":                       true,
	"outbounds[].tls.enabled":                      true,
	"outbounds[].tls.insecure":                     true,
	"outbounds[].tls.reality.enabled":              true,
	"outbounds[].tls.reality.public_key":           true,
	"outbounds[].tls.reality.short_id":             true,
	"outbounds[].tls.server_name":                  true,
	"outbounds[].tls.utls.enabled":                 true,
	"outbounds[].tls.utls.fingerprint":             true,
	"outbounds[].tolerance":                        true,
	"outbounds[].transport.early_data_header_name": true,
	"outbounds[].transport.host":                   true,
	"outbounds[].transport.host[]":                 true,
	"outbounds[].transport.max_early_data":         true,
	"outbounds[].transport.path":                   true,
	"outbounds[].transport.service_name":           true,
	"outbounds[].transport.type":                   true,
	"outbounds[].type":                             true,
	"outbounds[].udp_relay_mode":                   true,
	"outbounds[].url":                              true,
	"outbounds[].username":                         true,
	"outbounds[].uuid":                             true,
	"outbounds[].version":                          true,
	"outbounds[].zero_rtt_handshake":               true,
	"route.auto_detect_interface":                  true,
	"route.default_domain_resolver.server":         true,
	"route.final":                                  true,
	"route.rule_set[].format":                      true,
	"route.rule_set[].path":                        true,
	"route.rule_set[].tag":                         true,
	"route.rule_set[].type":                        true,
	"route.rules[].action":                         true,
	"route.rules[].domain_suffix[]":                true,
	"route.rules[].ip_cidr[]":                      true,
	"route.rules[].ip_is_private":                  true,
	"route.rules[].method":                         true,
	"route.rules[].network[]":                      true,
	"route.rules[].outbound":                       true,
	"route.rules[].port[]":                         true,
	"route.rules[].port_range[]":                   true,
	"route.rules[].process_name[]":                 true,
	"route.rules[].protocol":                       true,
	"route.rules[].protocol[]":                     true,
	"route.rules[].rule_set[]":                     true,
	"route.rules[].timeout":                        true,
}

// Ветки с произвольными именами ключей (заголовки HTTP).
var allowedPrefixes = []string{
	"outbounds[].transport.headers.",
}
